name = "newsnow"
main = "dist/output/server/index.mjs"
compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow-db"
database_id = "1e8c0ce6-2a0e-4abb-b3b7-df6d78ae5326"
